// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Security.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AlgoStoreUserData
    {
        /// <summary>
        /// Initializes a new instance of the AlgoStoreUserData class.
        /// </summary>
        public AlgoStoreUserData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AlgoStoreUserData class.
        /// </summary>
        public AlgoStoreUserData(string clientId = default(string), string firstName = default(string), string lastName = default(string), string fullName = default(string), string email = default(string), IList<UserRoleData> roles = default(IList<UserRoleData>))
        {
            ClientId = clientId;
            FirstName = firstName;
            LastName = lastName;
            FullName = fullName;
            Email = email;
            Roles = roles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Roles")]
        public IList<UserRoleData> Roles { get; set; }

    }
}
